### PR TITLE
Multiple fixes

### PR DESCRIPTION
**Pull request by eloycoto**
- [x] Cache changes
- [x] Envoy clusters config
- [x] Config load check using md5. 
- [x] Makefile. 

More to come.

### CODE REVIEW

**Comment by unleashed** [comment]
@eloycoto can you rebase again please? Also, I am not sure you enabled the ability for maintainers to edit your PR (I don't see anything indicating it, but I've never had the need to use that), but perhaps it would be best for you to use branches in this repo.

**Review by unleashed — APPROVED** [review]
Ok, let's just use this version as a base for further changes in code, since it should be working even if it still has issues.

**Comment by unleashed** [comment]
@eloycoto there are further clippy errors - you can check them by yourself by running `cargo clippy` before pushing changes, we can use a local git hook if you'd like to automate these.

**Comment by eloycoto** [comment]
bors r=@unleashed

**Pull request merged**
